title: Robby Aprianto
email: robprian@gmail.com
description: System Engineer | Linux & Infra Enthusiast
baseurl: ""
url: "https://robprian.github.io"

# Theme settings
theme: al-folio
permalink: /blog/:year/:title/

# Navigation
navbar_fixed: true
footer_fixed: true

# Blog settings
blog_name: Blog
blog_description: My writings and tutorials about Linux, Infrastructure, and DevOps
github_username: robprian

# Other settings
keywords: "System Engineer, Linux, Infrastructure, Blog, DevOps"
lang: en

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Social links
social:
  email: robprian@gmail.com
  github: robprian
  linkedin: robbyaprianto
  twitter: robbyyapr
  instagram: robbyyapr